### PR TITLE
Prettify json response

### PR DESCRIPTION
**Pull request by jverdeyen**
Untested and shameless stolen from https://github.com/qalex/dnsdock/commit/3f14a3bb0a563368d2eadba814262094b4f5483b

### CODE REVIEW

**Comment by ailispaw** [comment]
@jverdeyen Thank you for the PR.
Let me test.

**Comment by ailispaw** [comment]
LGTM

**Comment by ailispaw** [comment]
But I believe that it should be the original repo instead for the future release.
So I won't merge my master but my alpine branch, and taged `1.12.1.1-alpine`.

**Comment by ailispaw** [comment]
Merged at https://github.com/ailispaw/dnsdock/commit/fa7f4f50fd2078b01e449fb09e0b1c591d0d1263
And pushed `ailispaw/dnsdock:1.12.1.1-alpine` to the Docker Hub.
Thanks.

**Comment by ailispaw** [comment]
`tonistiigi/dnsdock` seems unreliable recently.
I have decided to maintain `alpine` branch as my master branch for a while.
The latest `ailispaw/dnsdock` will be tagged at `:latest` and `:alpine` as the same latest master image.

**Comment by jverdeyen** [comment]
We currently have a weird bug. We can't connect to any container via DNS unless we restart dnsdock. After a "while" we need to restart dnsdock again.

**Comment by ailispaw** [comment]
@jverdeyen That's weird.
Could you tell me which version of `ailispaw/barge`, docker and dnsdock you use?
I will try to figure that out.

**Comment by ailispaw** [comment]
I use your `Vagrantfile` and find something.

``` ruby
  config.vm.provision "docker" do |d|
    d.pull_images "ailispaw/dnsdock:1.12.1.1-alpine"
    d.run "ailispaw/dnsdock",
      args: "-v /var/run/docker.sock:/var/run/docker.sock -p 0.0.0.0:53:53/udp",
      restart: "always",
      daemonize: true
  end
```

It uses `ailispaw/dnsdock:latest` instead of `ailispaw/dnsdock:1.12.1.1-alpine`.
I guess it may use an old `:latest` image in your local cache.

FYI: in my case with your `Vagrantfile`,
I have a problem with `$vm_ip_address = "172.17.8.101"`, because `172.17.8.101` is in the range of `172.17.0.1/16` which is the default docker0 network.
(Docker used to use `172.17.42.1/24` as the default docker0 network.)
So sometime docker daemon assigns `172.18.0.1/16` instead because of that.

**Comment by ailispaw** [comment]
I checked with `ailispaw/dnsdock:1.12.0`, the old one, but it seems fine here.
How long does that "while" take?

**Comment by ailispaw** [comment]
@jverdeyen How's going?

I would like to switch back to upstream master.
On second thought, pretty print is not very good for Web API but a command line tool.
upstream v1.13.1 works good so far for me and have put a stripped version `ailispaw/dnsdock:1.13.1` for testing.
How do you think?

**Comment by jverdeyen** [comment]
@ailispaw 
We are now using `ailispaw/dnsdock:1.12.1.1-alpine`  (https://github.com/yappabe/vagrant-docker/blob/master/Vagrantfile#L74)

We don't have trouble in our VM (Mac) / Barge setup.
We're also using this dnsdock as a resolver on our staging env, which runs each project in containers (docker-compose config per project). And that's where we see this issue. I can't find anything in the dnsdock container logs. Setup: 

Ubuntu 14.04 with 

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

Using:

```
ailispaw/dnsdock          1.12.1-alpine       773b2e39a796        11 days ago         12.86 MB
```

I've added `nameserver 127.0.0.1` in `/etc/resolv.conf`
And forwarded port `:53`

```
3fa2faabb695        ailispaw/dnsdock:1.12.1-alpine   "/usr/bin/dnsdock -na"   7 days ago          Up 3 days                      0.0.0.0:53->53/udp            dnsdock
```

This way we can, for example, login with ssh and connect to a mysql container by it's dns dock alias.
This works fine, but we need to restart dnsdock after a few hours.

**Comment by jverdeyen** [comment]
@ailispaw about the pretty print, it's not a big deal :)

**Comment by ailispaw** [comment]
@jverdeyen 
How about the original `tonistiigi/dnsdock:amd64-1.13.1` or `ailispaw/dnsdock:1.13.1`?

> We are now using ailispaw/dnsdock:1.12.1.1-alpine (https://github.com/yappabe/vagrant-docker/blob/master/Vagrantfile#L74)

Normally you have to specify like below on run time as well as pulling. Your config will pull `ailispaw/dnsdock:latest` on run time again. Now they are the same though.

``` bash
  config.vm.provision "docker" do |d|
    d.pull_images "ailispaw/dnsdock:1.12.1.1-alpine"
    d.run "dnsdock",
      image: "ailispaw/dnsdock:1.12.1.1-alpine",
      args: "-v /var/run/docker.sock:/var/run/docker.sock -p 0.0.0.0:53:53/udp",
      restart: "always",
      daemonize: true
  end
```

**Comment by ailispaw** [comment]
> we need to restart dnsdock after a few hours.

Oh, a few hours. That's weird. And it doesn't happen in local env, but staging. Hmm.

**Comment by ailispaw** [comment]
You could use that setup on staging before, couldn't you?
I guess that Docker v1.9.1 & `tonistiigi/dnsdock:latest`.
I'm wondering what's difference between that and this time.

**Comment by ailispaw** [comment]
> @ailispaw about the pretty print, it's not a big deal :)

Thanks.

**Comment by ailispaw** [comment]
docker-compose (v2 format) creates a special network bridge with a different network address range for each project.
It might be related?

**Comment by ailispaw** [comment]
How about `docker-compose.yml`? same `version`?

**Comment by ailispaw** [comment]
@jverdeyen I created a new issue for this. #2

**Comment by ailispaw** [comment]
FYI:
https://github.com/tonistiigi/dnsdock/issues/68

**Pull request closed without merging**
